In [2]:
import pandas as pd
import numpy as np
#import scipy as sc
from datetime import datetime
import xml.etree.ElementTree as ET
import re
from os import listdir
from os.path import isfile, join
import seaborn as sns
import pickle
#reload(sys)
from copy import deepcopy
import matplotlib
import matplotlib.pyplot as plt
import xml.etree.ElementTree as ET
import urllib
import requests 
import json

from scipy.stats import percentileofscore
from scipy import stats
from sklearn.preprocessing import scale, robust_scale, minmax_scale, maxabs_scale
from scipy.stats import norm, skew

import pickle
import numpy as np 
import scipy
import pandas as pd
from scipy import stats
import itertools
import collections
import copy
import pickle
import operator
%matplotlib inline 
import sys
stdout = sys.stdout
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stdout = stdout

In [33]:
import itertools
import numpy as np
from scipy import stats
import pylab as pl
from sklearn import svm, linear_model
from sklearn.model_selection import cross_validate,train_test_split
from sklearn.model_selection import StratifiedShuffleSplit

In [36]:
def transform_pairwise(X, y, comb=True):
    X_new = []
    y_new = []
    y = np.asarray(y)
    if y.ndim == 1:
        y = np.c_[y, np.ones(y.shape[0])]

    start_index = 0
    balance_index = 0
    for i in range(1, X.shape[0]):
        if y[i, 1] != y[start_index, 1] or i == X.shape[0] - 1:
            for j in range(start_index, i - 1):
                for k in range(j + 1, i):
                    X_new.append(X[j] - X[k])
                    y_new.append(np.sign(y[k, 0] - y[j, 0]))
                    # output balanced classes
                    if y_new[-1] != (-1) ** balance_index:
                        y_new[-1] = - y_new[-1]
                        X_new[-1] = - X_new[-1]

                    balance_index += 1

            start_index = i

    return np.asarray(X_new), np.asarray(y_new).ravel()

In [76]:
a = np.array([1,3,4])
print a
print a.ravel()

[1 3 4]
[1 3 4]


In [52]:
rank_svm = svm.LinearSVC(dual=False)

In [81]:
y_trans[2]

1.0

In [82]:
x_trans[2]

array([-0.366674  ,  0.16666667,  0.349189  , -0.285714  , -0.615199  ])

In [54]:
rank_svm.fit(x_trans,y_trans)

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [70]:
svc = svm.LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=1e-05, verbose=0)

In [71]:
svc.fit(X_train,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=1e-05, verbose=0)

In [72]:
svc.coef_

array([[-0.66036657, -0.30306258, -0.24349378, -0.28623477,  0.0948626 ],
       [-0.00881399,  0.01994489, -0.25313795, -0.15058269, -0.17433186],
       [ 0.65430279,  0.26798626,  0.60484907,  0.42985846,  0.09578489]])

In [62]:
for i, coef in enumerate(rank_svm.coef_[0].tolist()):
    print('coef' + str(i), coef)

('coef0', 0.4106902643113828)
('coef1', 0.19597164443192444)
('coef2', 0.32201983330263023)
('coef3', 0.26475795413624886)
('coef4', 0.030656041398868378)


In [53]:
y_trans

array([-0., -0.,  1., ..., -0., -0., -0.])

In [ ]:
cv = model_selection.KFold(2)
    train, test = next(iter(cv.split(X)))

X_trans, y_trans = transform_pairwise(X[train], Y[train])

rank_svm = svm.LinearSVC(verbose=1,penalty=penalty, loss=loss, C=C, max_iter=max_iter, tol=tol, dual=dual).fit(X_trans, y_trans)

In [34]:
cv

StratifiedShuffleSplit(n_splits=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
            random_state=None, test_size=0.5, train_size=None)